### ISSUE TITLE
formParameters NamedParameter with empty Name

### ISSUE THREAD

**Issue by stefanoj3** [Jumpscale/go-raml#128]
```yaml
/some_endpoint:
  post:
    description:
    displayName: whatever
    body:
      formParameters:
        param1:
          required: true
          type: string
        param2:
          required: true
          type: string
        param3:
          required: false
          type: string
```

While reading a file with a similar structure the named parameters that are part of the specified resource have an empty Name field for the NamedParameter/s contained in:
```go
resource.Post.Bodies.FormParameters
```
Other fields like Required, Description, DisplayName, and Type are filled, but the Name is empty.

Any clue?
