### ISSUE TITLE
`type: object` doesn't handled correctly in response body

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#143]
Both raml should produce same code
```
          application/json: # media type
            properties:
                message:
                  type: string
```

```
      application/json: # media type
            type: object
            properties:
                message:
                  type: string
```

But it is not.
