### ISSUE TITLE
python: init of optional object fails

### ISSUE THREAD

**Issue by RubenMattan** [Jumpscale/go-raml#278]
```yaml
Work:
  properties:
    company?: string

Profile:
  properties:
    id: string
    firstName: string
    lastName: string
    work?: Work
```
```json
{"id": "xxx", "firstName": "Ruben", "lastName": "Mattan", "work": {}}
```
```python
class Work(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(company=None):
        """
        :type company: str
        :rtype: Work
        """

        return Work(
            company=company,
        )

    def __init__(self, json=None, **kwargs):
        if not json and not kwargs:
            raise ValueError('No data or kwargs present')
```

This will always give you the error 'No data or kwargs present' because json is an empty dict
