### ISSUE TITLE
Support cookie authentification

### ISSUE THREAD

**Issue by maxux** [Jumpscale/go-raml#323]
In some context, you needs to provide a specific cookie with special contents to provide some kind of authentification. RAML specficiation allows `cookies` fields, but not clearly defined for authentification.

It would be cool to support a way to, at least, provide additional cookies during requests, when cookies are specified on RAML specification.

**Comment by iwanbk** [comment]
which languages and server/client you want it first?

So i can implement it -> you test -> you give feedback -> i implement it for other languages and server/client

**Comment by maxux** [comment]
Python at first.
I could introduce it easily with: https://github.com/zero-os/0-hub/commit/5dbc135dafb44b42fce9572ddf8b4cffa0719500
This introduce only a small change and calling `set_token` enable authentification. But honestly, I don't know how to link this with RAML.

In this case, I used this kind of `securedBy` but is that good enough ? 
```
securitySchemes:
  cookies:
    description: Cookie authentification
    type: Pass Through
    describedBy:
      headers:
        cookies:
          type: string
```
