### ISSUE TITLE
Incorrect python generation for raml union

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/go-raml#357]
If you generate a python client for this raml
```
types:
  Node:
    type: object
    description: Node in the Zero-OS  0 Rest API
    properties:
      id: string | integer[]
      ipaddress: string
      status:
        enum: [running, halted]
        description: Status of the node
      hostname: string
```
the generated class for Node, will assume that the property `id` is of type list and can be a list of integer  but actually `string | integer[]` means that `id` can either be a string or a list of integers, on the other hand, `(string | integer)[]` means the id can be a list of either string or integer. 
And actually, the struct we use to initialize the field in the generator, has isList property so each type can either be a list or not, it is not possible for a type to support both cases.
I am not sure if we should support this `string | integer[]` or not but if we won't support it then may be we can at least document the scenarios we are not planning on supporting. I am sure there are already other complex raml scenarios that aren't supported.
