### ISSUE TITLE
Enum not properly translated to a go type

### ISSUE THREAD

**Issue by robvanmieghem** [Jumpscale/go-raml#37]
Currently the following raml type
```
  Invitation:
    properties:
        user: string
        role:
          type: string
          enum: [owner, member]
        created: date
```
is converted to 
```
type Invitation struct {
	Created Date     `json:"created"`
	Role    []string `json:"role"`
	User    string   `json:"user"`
}
```
