### ISSUE TITLE
Broken enum generation in capnp

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/go-raml#378]
Schemas for enums are generated correctly only when it is a field in a type for example:
```
types:
  GWNIC:
    type: object
    properties:
      type:
        enum: [zerotier, vxlan, vlan, default, bridge]
      id:
        type:string
```
for the raml above, an enum schema will be correctly generated for the `type` field. However, for the raml below, when the enum is defined as a parent type, the generated schema will not be enum, it will be an empty struct with no fields.
```
types:
  HTTPType:
    enum: [http, https]
```
