### ISSUE TITLE
python server: incorrect schema load

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/go-raml#388]
When generating a python server, the generated schema import is incorrect for types starting with lower case.
so if you have this type in raml for example
```
acl:
  type: object
  properties:
    uid:
      required: true
      description: is unique id for the acl, increments
      type: number
      format: int32
    aci:
      required: true
      description: list of access control items
      type: ACI[]
    hash:
      required: true
      description: md5 hash of concatenation of ACI hashes, used to find this acl to avoid duplicates
      type: text
```
The generated schema validator will be acl_schema.json however it will be loaded using `Acl_schema.json` which crashes because the file doesnt exist.

```
Acl_schema =  JSON.load(open(dir_path + '/schema/Acl_schema.json'))
```
