### ISSUE TITLE
Go: Use pointer for non-required structs

### ISSUE THREAD

**Issue by vennekilde** [Jumpscale/go-raml#472]
None required structs are being returned as part of the encoded JSON response, which isn't really that great

If you have lets say a RAML spec like
```
types:
    Parent:
        properties:
            name:
                type: string
            child:
                type: Child
                required: false
    Child:
        properties:
            name:
                type: string
```
Would generate the follwing Parent struct 
```
type Parent struct {
	Child Child  `json:"child,omitempty"`
	Name  string `json:"name" validate:"nonzero"`
}
```
The problem is that the Child is not a pointer, so it will never be empty and will therefor be included as part of the json response

You already somewhat do this, as i thought that the code wouldn't even be able to compile if you attempted to set Child type to Parent, as it would create an infinite nesting loop, though that isn't the case, as the generated struct in that case will correctly use a pointer to avoid that particular issue
