### ISSUE TITLE
Incorrect json schema generation when property is required and nullable

### ISSUE THREAD

**Issue by DainSwechs** [Jumpscale/go-raml#477]
* Go: go1.12.7 linux/amd64
* Python: 3.6.8
* OS: Ubuntu 18.04.3 x64

Basic schema generation example

`test.raml`
```yaml
#%RAML 1.0
title: test raml
mediaType: application/json

types:
    sometype:
        properties:
            field1:
                required: true
                type: string
            field2:
                required: true
                type: string
```
```bash
$ go-raml server -l python --dir ./testserver --ramlfile test.raml
```
**generates proper schema file**

```bash
$ cat testserver/handlers/schema/sometype_schema.json 
```
```json
{
        "$schema": "http://json-schema.org/schema#",
        "type": "object",
        "properties": {
                "field1": {
                        "type": "string"
                },
                "field2": {
                        "type": "string"
                }
        },
        "required": [
                "field1",
                "field2"
        ]
}
```
**Let's make one of the required fields also nullable (RAML 1.0 compliant)**
`test_2.raml`
```yaml
#%RAML 1.0
title: test raml
mediaType: application/json

types:
    sometype:
        properties:
            field1:
                required: true
                type: string | nil
            field2:
                required: true
                type: string
```

```bash
$ go-raml server -l python --dir ./testserver2 --ramlfile test_2.raml
```

**results in broken json schema that will not properly validate the type**
``` bash
$ cat testserver2/handlers/schema/sometype_schema.json 
```
```
{
        "$schema": "http://json-schema.org/schema#",
        "type": "object",
        "properties": {
                "field2": {
                        "type": "string"
                }
        },
        "required": [
                "field2"
        ]
}
```

## Workaround
1. Leave off the ` | nil` portion in your .raml file before server generation.
1. After generation, edit schema.json files manually and change `"type": "string"` to `"type": ["string", "null"]`
