### ISSUE TITLE
support for optional properties in resource type and traits

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#76]
example:
```
#%RAML 1.0
title: Example of Optional Properties of Types Defined in Trait
traits:
  - hasPayload:
      body:
        application/json:
          properties:
            name:
            address\?:
            location?:
/servers:
  post:
    is: [ hasPayload ]
    # will have application/json body with 'name' required property,
    # 'address' optional property, but without 'location' property
```
