### ISSUE TITLE
check for raml1.0-rc type inheritance

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#85]

**Comment by iwanbk** [comment]
In RC1

RC1 is really strict on how inheritance works for types. So the following example is invalid in RC1:
```
types:
  Number1:
   type: number
   minimum: 4
  Number2:
   type: number
   maximum: 10
  Number3: [ Number1, Number2]
```

In RC2

RC2 has more simplistic rules and allows a bit more freedom on inheritance. The following example is valid in RC2:
```
types:
  Number1:
   type: number
   minimum: 4
  Number2:
   type: number
   maximum: 10
  Number3: [ Number1, Number2]
```
