### ISSUE TITLE
RC2 allows to define a type declaration inside the `type` facet

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#96]
The inline declaration could be in these places
- [x] in property's properties (462f88ad788551f1bfb8b84f45fdd67d9cf0e8fe) of a type, recursive: 6a20225c97c6a2542ea368933b8faf4ea4341d44
- [x] propertiy's item of a type (0b1dc8046c448402149d78a40e7cd24f239a60a0)
- [x] in type's type (partial support: see https://github.com/Jumpscale/go-raml/issues/228#issuecomment-285037273)
- [x] in method body's properties
- [x] in method body's type

from https://github.com/raml-org/raml-spec/wiki/RAML-1.0-RC1-vs-RC2

In RC1
You could not have a type declaration as the value of `type`, or include it from an external source. So the following is invalid in RC1:

```
types:
  Next:
    type:
      properties:
        another: string
    properties:
      name: string
```

In RC2
With regards to a consistent approach throughout the specification and how we handle different types/schemas, RC2 allows to define a type declaration inside the `type` facet. So the following is valid in RC2:

```
types:
  Next:
    type:
      properties:
        another: string
    properties:
      name: string
```

**Comment by iwanbk** [comment]
Finally have the time to really check it today.

I think it is best for the parser to handle it entirely.

If the property declares (inlining) a new type, the parser do these:
- create new type with name = type name + property name
- change the property type to this newly created type

example
```
Action:
    properties:
      name: string
      
      recurring:
        type: object
        properties:
          period:
            type: integer
     
````
Will produce same code as

```
ActionRecurring:
  type: object
  properties:
     period:
        type: integer

Action:
    properties:
      name: string
      code: string
      recurring: ActionRecurring    
```

Which means the generated code of the new type is not inlined, it instead creates a new type (or struct in case of Go)
What do you think @zaibon? I took above raml snippet from your example at #226.
