### ISSUE TITLE
Allow arrays as resource types and traits parameters

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#99]
example:

```
#%RAML 1.0
title: My Sample API
traits:
  ordered:
    queryParameters:
      orderBy:
        description: Order by field
        enum: <<filterValues>>
/people:
  is: [ ordered: { filterValues: [ age, height ] } ]
```

more details:
https://github.com/raml-org/raml-spec/issues/85#issuecomment-216761558
